export const BRAND_CODES: Record<string, string> = {
  CH: "Conrad",
  DT: "DoubleTree",
  ES: "Embassy Suites",
  GI: "Hilton Garden Inn",
  GU: "Graduate",
  GV: "Hilton Grand Vacations",
  HI: "Hilton",
  HP: "Hampton",
  HT: "Home2 Suites",
  HW: "Homewood Suites",
  LX: "Small Luxury Hotels of the World",
  ND: "NoMad",
  OL: "LXR",
  OU: "AutoCamp",
  PE: "Spark by Hilton",
  PO: "Tempo",
  PY: "Canopy",
  QQ: "Curio Collection",
  RU: "Tru",
  SA: "Signia",
  UA: "Motto",
  UP: "Tapestry Collection",
  WA: "Waldorf Astoria",
};
