import { PrismaClient, BookingSourceType, CertType, BenefitType } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const bookings = [
    {
      id: 16,
      hotelChainId: 2,
      hotelChainSubBrandId: 31,
      propertyName: "Duxton Reserve Singapore",
      checkIn: "2026-03-02T00:00:00.000Z",
      checkOut: "2026-03-05T00:00:00.000Z",
      numNights: 3,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [
        { certType: "marriott_50k" },
        { certType: "marriott_50k" },
        { certType: "marriott_50k" },
      ],
      benefits: [],
    },
    {
      id: 17,
      hotelChainId: 3,
      hotelChainSubBrandId: 52,
      propertyName: "Park Hyatt Kuala Lumpur",
      checkIn: "2026-03-06T00:00:00.000Z",
      checkOut: "2026-03-07T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [{ certType: "hyatt_cat1_7" }],
      benefits: [],
    },
    {
      id: 18,
      hotelChainId: 4,
      hotelChainSubBrandId: 72,
      propertyName: "Holiday Inn Express KL City Centre",
      checkIn: "2026-03-06T00:00:00.000Z",
      checkOut: "2026-03-07T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "58",
      taxAmount: "11",
      totalCost: "69",
      creditCardId: 2,
      shoppingPortalId: 2,
      portalCashbackRate: "0.24",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1160,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: null,
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 19,
      hotelChainId: 4,
      hotelChainSubBrandId: 69,
      propertyName: "Hotel Indigo Kuala Lumpur",
      checkIn: "2026-03-07T00:00:00.000Z",
      checkOut: "2026-03-13T00:00:00.000Z",
      numNights: 6,
      pretaxCost: "528",
      taxAmount: "43",
      totalCost: "571",
      creditCardId: 4,
      shoppingPortalId: 2,
      portalCashbackRate: "0.12",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 10560,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 20,
      hotelChainId: 3,
      hotelChainSubBrandId: 56,
      propertyName: "Hyatt Centric Kuala Lumpur",
      checkIn: "2026-03-13T00:00:00.000Z",
      checkOut: "2026-03-20T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 24500,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 21,
      hotelChainId: 5,
      hotelChainSubBrandId: 227,
      propertyName: "Sunway Velocity Hotel",
      checkIn: "2026-03-20T00:00:00.000Z",
      checkOut: "2026-03-22T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "150",
      taxAmount: "13",
      totalCost: "163",
      creditCardId: 2,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1050,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 22,
      hotelChainId: 5,
      hotelChainSubBrandId: 82,
      propertyName: "Park Royal Serviced Suites KL",
      checkIn: "2026-03-22T00:00:00.000Z",
      checkOut: "2026-03-24T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "166",
      taxAmount: "14",
      totalCost: "180",
      creditCardId: 2,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1162,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 23,
      hotelChainId: 5,
      hotelChainSubBrandId: 215,
      propertyName: "Park Royal Collection KL",
      checkIn: "2026-03-24T00:00:00.000Z",
      checkOut: "2026-03-26T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "299",
      taxAmount: "24",
      totalCost: "323",
      creditCardId: 2,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 2093,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 24,
      hotelChainId: 2,
      hotelChainSubBrandId: 683,
      propertyName: "citizenM Kuala Lumpur",
      checkIn: "2026-03-26T00:00:00.000Z",
      checkOut: "2026-03-27T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "60",
      taxAmount: "4",
      totalCost: "64",
      creditCardId: 2,
      shoppingPortalId: 3,
      portalCashbackRate: "6",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1050,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 25,
      hotelChainId: 3,
      hotelChainSubBrandId: 56,
      propertyName: "Hyatt Centric Kuala Lumpur",
      checkIn: "2026-03-27T00:00:00.000Z",
      checkOut: "2026-04-03T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 35000,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 26,
      hotelChainId: 3,
      hotelChainSubBrandId: 58,
      propertyName: "Hyatt Place Bukit Jalil",
      checkIn: "2026-04-03T00:00:00.000Z",
      checkOut: "2026-04-10T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 35000,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: 27,
      hotelChainId: 2,
      hotelChainSubBrandId: 40,
      propertyName: "Moxy KL Chinatown",
      checkIn: "2026-04-10T00:00:00.000Z",
      checkOut: "2026-04-14T00:00:00.000Z",
      numNights: 4,
      pretaxCost: "257",
      taxAmount: "46",
      totalCost: "303",
      creditCardId: 2,
      shoppingPortalId: 3,
      portalCashbackRate: "6",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 4498,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [{ benefitType: "free_breakfast" }],
    },
    {
      id: 28,
      hotelChainId: 2,
      hotelChainSubBrandId: 288,
      propertyName: "The Serangoon House Little India",
      checkIn: "2026-04-14T00:00:00.000Z",
      checkOut: "2026-04-15T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "186",
      taxAmount: "37",
      totalCost: "223",
      creditCardId: 2,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 3255,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [
        { benefitType: "free_breakfast" },
        { benefitType: "dining_credit", dollarValue: 75 },
      ],
    },
    {
      id: 29,
      hotelChainId: 6,
      hotelChainSubBrandId: 96,
      propertyName: "ibis Styles Ambassador ICN",
      checkIn: "2026-04-15T00:00:00.000Z",
      checkOut: "2026-04-16T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "82",
      taxAmount: "9",
      totalCost: "91",
      creditCardId: 2,
      shoppingPortalId: 1,
      portalCashbackRate: "2",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 150,
      pointsRedeemed: null,
      currency: "USD",
      originalAmount: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
  ];

  for (const b of bookings) {
    const { certificates, benefits, ...bookingData } = b;

    const payload = {
      ...bookingData,
      bookingSource: bookingData.bookingSource as BookingSourceType,
      certificates: {
        create: certificates.map((c) => ({ certType: c.certType as CertType })),
      },
      benefits: {
        create: benefits.map((b) => ({
          benefitType: b.benefitType as BenefitType,
          dollarValue: b.dollarValue ? Number(b.dollarValue) : null,
        })),
      },
    };

    await prisma.booking.upsert({
      where: { id: b.id },
      update: {
        ...payload,
        certificates: {
          deleteMany: {},
          ...payload.certificates,
        },
        benefits: {
          deleteMany: {},
          ...payload.benefits,
        },
      },
      create: payload,
    });
  }

  console.log("Bookings restored/upserted successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
