import { PrismaClient, BookingSourceType, CertType, BenefitType } from "@prisma/client";
import { HOTEL_ID, SUB_BRAND_ID } from "../src/lib/constants";
import { CREDIT_CARD_ID, SHOPPING_PORTAL_ID } from "./seed-ids";

const prisma = new PrismaClient();

interface BookingSeedData {
  id: string;
  hotelChainId: string;
  hotelChainSubBrandId: string | null;
  propertyName: string;
  checkIn: string;
  checkOut: string;
  numNights: number;
  pretaxCost: string;
  taxAmount: string;
  totalCost: string;
  creditCardId: string | null;
  shoppingPortalId: string | null;
  portalCashbackRate: string | null;
  portalCashbackOnTotal: boolean;
  loyaltyPointsEarned: number | null;
  pointsRedeemed: number | null;
  currency: string;
  exchangeRate: number | null;
  bookingSource: string | null;
  otaAgencyId: string | null;
  notes: string | null;
  certificates: { certType: string }[];
  benefits: { benefitType: string; dollarValue?: number | string | null }[];
}

export async function seedBookings(userId: string) {
  const bookings: BookingSeedData[] = [
    {
      id: "clas2mljema779deuxi5mhuee",
      hotelChainId: HOTEL_ID.MARRIOTT,
      hotelChainSubBrandId: SUB_BRAND_ID.MARRIOTT.AUTOGRAPH_COLLECTION,
      propertyName: "Duxton Reserve Singapore",
      checkIn: "2026-03-02T00:00:00.000Z",
      checkOut: "2026-03-05T00:00:00.000Z",
      numNights: 3,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [
        { certType: "marriott_50k" },
        { certType: "marriott_50k" },
        { certType: "marriott_50k" },
      ],
      benefits: [],
    },
    {
      id: "c83ak8zknu6pwcvqhbfhm7ekv",
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.PARK_HYATT,
      propertyName: "Park Hyatt Kuala Lumpur",
      checkIn: "2026-03-06T00:00:00.000Z",
      checkOut: "2026-03-07T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [{ certType: "hyatt_cat1_7" }],
      benefits: [],
    },
    {
      id: "ct05t6xeejpm9q6dxgtvei3r8",
      hotelChainId: HOTEL_ID.IHG,
      hotelChainSubBrandId: SUB_BRAND_ID.IHG.HOLIDAY_INN_EXPRESS,
      propertyName: "Holiday Inn Express KL City Centre",
      checkIn: "2026-03-06T00:00:00.000Z",
      checkOut: "2026-03-07T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "221.45",
      taxAmount: "41.63",
      totalCost: "263.08",
      creditCardId: CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.TOPCASHBACK,
      portalCashbackRate: "0.24",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1122,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: 0.25324,
      bookingSource: null,
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "c4mv6rvmc0pln9mk7txqlshkm",
      hotelChainId: HOTEL_ID.IHG,
      hotelChainSubBrandId: SUB_BRAND_ID.IHG.HOTEL_INDIGO,
      propertyName: "Hotel Indigo Kuala Lumpur",
      checkIn: "2026-03-07T00:00:00.000Z",
      checkOut: "2026-03-13T00:00:00.000Z",
      numNights: 6,
      pretaxCost: "2080.50",
      taxAmount: "166.42",
      totalCost: "2246.92",
      creditCardId: CREDIT_CARD_ID.WELLS_FARGO_AUTOGRAPH,
      shoppingPortalId: SHOPPING_PORTAL_ID.TOPCASHBACK,
      portalCashbackRate: "0.12",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 10544,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: 0.253408,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cufi5o67mbga7e8an9rvsb2vn",
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_CENTRIC,
      propertyName: "Hyatt Centric Kuala Lumpur",
      checkIn: "2026-03-13T00:00:00.000Z",
      checkOut: "2026-03-20T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 24500,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "ctshv1is5aacu6rwsrsebfyxi",
      hotelChainId: HOTEL_ID.GHA_DISCOVERY,
      hotelChainSubBrandId: SUB_BRAND_ID.GHA_DISCOVERY.SUNWAY,
      propertyName: "Sunway Velocity Hotel",
      checkIn: "2026-03-20T00:00:00.000Z",
      checkOut: "2026-03-22T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "588.00",
      taxAmount: "47.04",
      totalCost: "635.04",
      creditCardId: CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1043,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cnrxt78gdols3zb0bxsmaciaq",
      hotelChainId: HOTEL_ID.GHA_DISCOVERY,
      hotelChainSubBrandId: SUB_BRAND_ID.GHA_DISCOVERY.PARKROYAL,
      propertyName: "Park Royal Serviced Suites KL",
      checkIn: "2026-03-22T00:00:00.000Z",
      checkOut: "2026-03-24T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "650.00",
      taxAmount: "52.00",
      totalCost: "702.00",
      creditCardId: CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1153,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cwy9rm93feastnxmna5u75arp",
      hotelChainId: HOTEL_ID.GHA_DISCOVERY,
      hotelChainSubBrandId: SUB_BRAND_ID.GHA_DISCOVERY.PARKROYAL_COLLECTION,
      propertyName: "Park Royal Collection KL",
      checkIn: "2026-03-24T00:00:00.000Z",
      checkOut: "2026-03-26T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "1170.00",
      taxAmount: "93.60",
      totalCost: "1263.60",
      creditCardId: CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 2075,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cuj2d4xsen4rntp0ujp9gvjb0",
      hotelChainId: HOTEL_ID.MARRIOTT,
      hotelChainSubBrandId: SUB_BRAND_ID.MARRIOTT.CITIZENM,
      propertyName: "citizenM Kuala Lumpur",
      checkIn: "2026-03-26T00:00:00.000Z",
      checkOut: "2026-03-27T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "233.00",
      taxAmount: "18.64",
      totalCost: "251.64",
      creditCardId: CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.BRITISH_AIRWAYS,
      portalCashbackRate: "6",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1033,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cscx18qakqticrsl6g6xvh7ha",
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_CENTRIC,
      propertyName: "Hyatt Centric Kuala Lumpur",
      checkIn: "2026-03-27T00:00:00.000Z",
      checkOut: "2026-04-03T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 35000,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cy58uq56kllc6feidriho04yh",
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_PLACE,
      propertyName: "Hyatt Place Bukit Jalil",
      checkIn: "2026-04-03T00:00:00.000Z",
      checkOut: "2026-04-10T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      creditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 35000,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cc2gaeqcxn2mj300o28duzvd5",
      hotelChainId: HOTEL_ID.MARRIOTT,
      hotelChainSubBrandId: SUB_BRAND_ID.MARRIOTT.MOXY,
      propertyName: "Moxy KL Chinatown",
      checkIn: "2026-04-10T00:00:00.000Z",
      checkOut: "2026-04-14T00:00:00.000Z",
      numNights: 4,
      pretaxCost: "1008.61",
      taxAmount: "181.55",
      totalCost: "1190.16",
      creditCardId: CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.BRITISH_AIRWAYS,
      portalCashbackRate: "6",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 4473,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [{ benefitType: "free_breakfast" }],
    },
    {
      id: "cpmpa0buq8jl85t5wcv13wvi8",
      hotelChainId: HOTEL_ID.MARRIOTT,
      hotelChainSubBrandId: SUB_BRAND_ID.MARRIOTT.TRIBUTE_PORTFOLIO,
      propertyName: "The Serangoon House Little India",
      checkIn: "2026-04-14T00:00:00.000Z",
      checkOut: "2026-04-15T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "235.00",
      taxAmount: "46.75",
      totalCost: "281.75",
      creditCardId: CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.BRITISH_AIRWAYS,
      portalCashbackRate: "6",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 3215,
      pointsRedeemed: null,
      currency: "SGD",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [
        { benefitType: "free_breakfast" },
        { benefitType: "dining_credit", dollarValue: "75" },
      ],
    },
    {
      id: "cmgz12kjvzu90qvn5wxrki7ui",
      hotelChainId: HOTEL_ID.ACCOR,
      hotelChainSubBrandId: SUB_BRAND_ID.ACCOR.IBIS_STYLES,
      propertyName: "ibis Styles Ambassador ICN",
      checkIn: "2026-04-15T00:00:00.000Z",
      checkOut: "2026-04-16T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "119000.00",
      taxAmount: "11900.00",
      totalCost: "130900.00",
      creditCardId: CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.RAKUTEN,
      portalCashbackRate: "2",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 147,
      pointsRedeemed: null,
      currency: "KRW",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
  ];

  for (const b of bookings) {
    const { certificates, benefits, ...bookingData } = b;

    const payload = {
      ...bookingData,
      bookingSource: bookingData.bookingSource as BookingSourceType,
      certificates: {
        create: certificates.map((c) => ({ certType: c.certType as CertType })),
      },
      benefits: {
        create: benefits.map((b) => ({
          benefitType: b.benefitType as BenefitType,
          dollarValue: b.dollarValue ? Number(b.dollarValue) : null,
        })),
      },
    };

    await prisma.booking.upsert({
      where: { id: b.id },
      update: {
        ...payload,
        userId,
        certificates: {
          deleteMany: {},
          ...payload.certificates,
        },
        benefits: {
          deleteMany: {},
          ...payload.benefits,
        },
      },
      create: { ...payload, userId },
    });
  }

  console.log("Bookings restored/upserted successfully");
}

if (require.main === module) {
  const standaloneUserId = process.env.SEED_USER_ID ?? "";
  seedBookings(standaloneUserId)
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
