import {
  PrismaClient,
  BookingSourceType,
  CertType,
  BenefitType,
  AccommodationType,
  PaymentTiming,
} from "@prisma/client";
import { HOTEL_ID, SUB_BRAND_ID } from "../src/lib/constants";
import { USER_CREDIT_CARD_ID, SHOPPING_PORTAL_ID, OTA_AGENCY_ID } from "./seed-ids";

const prisma = new PrismaClient();

interface BookingSeedData {
  id: string;
  accommodationType: AccommodationType;
  hotelChainId: string | null;
  hotelChainSubBrandId: string | null;
  propertyName: string;
  countryCode: string;
  city: string;
  checkIn: string;
  checkOut: string;
  numNights: number;
  pretaxCost: string;
  taxAmount: string;
  totalCost: string;
  userCreditCardId: string | null;
  shoppingPortalId: string | null;
  portalCashbackRate: string | null;
  portalCashbackOnTotal: boolean;
  loyaltyPointsEarned: number | null;
  pointsRedeemed: number | null;
  currency: string;
  exchangeRate: number | null;
  paymentTiming?: PaymentTiming; // omit to use DB default (postpaid)
  bookingDate?: string | null;
  bookingSource: string | null;
  otaAgencyId: string | null;
  notes: string | null;
  certificates: { certType: string }[];
  benefits: { benefitType: string; dollarValue?: number | string | null }[];
}

export async function seedBookings(userId: string) {
  const bookings: BookingSeedData[] = [
    {
      id: "cmmw3qaf60007la04rh6q7dhp",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HILTON,
      hotelChainSubBrandId: SUB_BRAND_ID.HILTON.HILTON,
      propertyName: "Hilton Zurich Airport",
      countryCode: "CH",
      city: "Opfikon",
      checkIn: "2026-01-20T00:00:00.000Z",
      checkOut: "2026-01-21T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "99",
      taxAmount: "0",
      totalCost: "99",
      userCreditCardId: USER_CREDIT_CARD_ID.AMEX_BUSINESS_PLATINUM,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 2511,
      pointsRedeemed: null,
      currency: "CHF",
      exchangeRate: 1.253846,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3rjfd0003k5040vk8la4y",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.ACCOR,
      hotelChainSubBrandId: SUB_BRAND_ID.ACCOR.MONDRIAN,
      propertyName: "Mondrian Singapore Duxton",
      countryCode: "SG",
      city: "Singapore",
      checkIn: "2026-01-21T00:00:00.000Z",
      checkOut: "2026-01-23T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "528",
      taxAmount: "93",
      totalCost: "621",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 2021,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      paymentTiming: "prepaid" as PaymentTiming,
      bookingDate: "2025-12-30T00:00:00.000Z",
      bookingSource: "ota",
      otaAgencyId: OTA_AGENCY_ID.CHASE_EDIT,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3sy6f000bju04zqn63sfh",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_REGENCY,
      propertyName: "Hyatt Regency Taoyuan International Airport",
      countryCode: "TW",
      city: "Dayuan District",
      checkIn: "2026-01-23T00:00:00.000Z",
      checkOut: "2026-01-24T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      userCreditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 9500,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3uggs002rju04mzl4e1gu",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.ACCOR,
      hotelChainSubBrandId: SUB_BRAND_ID.ACCOR.MONDRIAN,
      propertyName: "Mondrian Hong Kong",
      countryCode: "HK",
      city: "Kowloon",
      checkIn: "2026-01-24T00:00:00.000Z",
      checkOut: "2026-01-26T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "521",
      taxAmount: "68",
      totalCost: "589",
      userCreditCardId: USER_CREDIT_CARD_ID.AMEX_BUSINESS_PLATINUM_2,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1994,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      paymentTiming: "prepaid" as PaymentTiming,
      bookingDate: "2025-09-21T00:00:00.000Z",
      bookingSource: "ota",
      otaAgencyId: OTA_AGENCY_ID.AMEX_THC,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3wtdl002jk50453obr8rx",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.ALILA,
      propertyName: "Alila Bangsar Kuala Lumpur",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-01-26T00:00:00.000Z",
      checkOut: "2026-02-02T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "2819.68",
      taxAmount: "294.62",
      totalCost: "3114.3",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_WORLD_OF_HYATT,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 4672,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: 0.251952,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmx04o030003l804fp639zxp",
      accommodationType: "apartment" as AccommodationType,
      hotelChainId: null,
      hotelChainSubBrandId: null,
      propertyName: "Island 88",
      countryCode: "MY",
      city: "George Town",
      checkIn: "2026-02-02T00:00:00.000Z",
      checkOut: "2026-03-02T00:00:00.000Z",
      numNights: 28,
      pretaxCost: "979.95",
      taxAmount: "233.15",
      totalCost: "1213.1",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.BRITISH_AIRWAYS,
      portalCashbackRate: "2",
      portalCashbackOnTotal: true,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "ota",
      otaAgencyId: OTA_AGENCY_ID.AIRBNB,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "clas2mljema779deuxi5mhuee",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.MARRIOTT,
      hotelChainSubBrandId: SUB_BRAND_ID.MARRIOTT.AUTOGRAPH_COLLECTION,
      propertyName: "Duxton Reserve Singapore, Autograph Collection",
      countryCode: "SG",
      city: "Singapore",
      checkIn: "2026-03-02T00:00:00.000Z",
      checkOut: "2026-03-05T00:00:00.000Z",
      numNights: 3,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      userCreditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 0,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [
        { certType: "marriott_50k" },
        { certType: "marriott_50k" },
        { certType: "marriott_50k" },
      ],
      benefits: [],
    },
    {
      id: "c83ak8zknu6pwcvqhbfhm7ekv",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.PARK_HYATT,
      propertyName: "Park Hyatt Kuala Lumpur",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-05T00:00:00.000Z",
      checkOut: "2026-03-06T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      userCreditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 0,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [{ certType: "hyatt_cat1_7" }],
      benefits: [],
    },
    {
      id: "ct05t6xeejpm9q6dxgtvei3r8",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.IHG,
      hotelChainSubBrandId: SUB_BRAND_ID.IHG.HOLIDAY_INN_EXPRESS,
      propertyName: "Holiday Inn Express Kuala Lumpur City Centre by IHG",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-06T00:00:00.000Z",
      checkOut: "2026-03-07T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "221.45",
      taxAmount: "41.63",
      totalCost: "263.08",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.TOPCASHBACK,
      portalCashbackRate: "0.24",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1122,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: 0.25324,
      bookingSource: null,
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "c4mv6rvmc0pln9mk7txqlshkm",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.IHG,
      hotelChainSubBrandId: SUB_BRAND_ID.IHG.HOTEL_INDIGO,
      propertyName: "Hotel Indigo Kuala Lumpur on the Park by IHG",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-07T00:00:00.000Z",
      checkOut: "2026-03-13T00:00:00.000Z",
      numNights: 6,
      pretaxCost: "2080.5",
      taxAmount: "166.42",
      totalCost: "2246.92",
      userCreditCardId: USER_CREDIT_CARD_ID.WELLS_FARGO_AUTOGRAPH,
      shoppingPortalId: SHOPPING_PORTAL_ID.TOPCASHBACK,
      portalCashbackRate: "0.12",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 10544,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: 0.253408,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cufi5o67mbga7e8an9rvsb2vn",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_CENTRIC,
      propertyName: "Hyatt Centric City Centre Kuala Lumpur",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-13T00:00:00.000Z",
      checkOut: "2026-03-20T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      userCreditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 24500,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "ctshv1is5aacu6rwsrsebfyxi",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.GHA_DISCOVERY,
      hotelChainSubBrandId: SUB_BRAND_ID.GHA_DISCOVERY.SUNWAY,
      propertyName: "Sunway Velocity Hotel",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-20T00:00:00.000Z",
      checkOut: "2026-03-22T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "588",
      taxAmount: "47.04",
      totalCost: "635.04",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cnrxt78gdols3zb0bxsmaciaq",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.GHA_DISCOVERY,
      hotelChainSubBrandId: SUB_BRAND_ID.GHA_DISCOVERY.PARKROYAL,
      propertyName: "PARKROYAL Serviced Suites Kuala Lumpur",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-22T00:00:00.000Z",
      checkOut: "2026-03-24T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "650",
      taxAmount: "52",
      totalCost: "702",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cwy9rm93feastnxmna5u75arp",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.GHA_DISCOVERY,
      hotelChainSubBrandId: SUB_BRAND_ID.GHA_DISCOVERY.PARKROYAL_COLLECTION,
      propertyName: "PARKROYAL COLLECTION Kuala Lumpur",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-24T00:00:00.000Z",
      checkOut: "2026-03-26T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "1170",
      taxAmount: "93.6",
      totalCost: "1263.6",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_app",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cuj2d4xsen4rntp0ujp9gvjb0",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.MARRIOTT,
      hotelChainSubBrandId: SUB_BRAND_ID.MARRIOTT.CITIZENM,
      propertyName: "citizenM Kuala Lumpur",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-26T00:00:00.000Z",
      checkOut: "2026-03-27T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "228",
      taxAmount: "18.24",
      totalCost: "246.24",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.BRITISH_AIRWAYS,
      portalCashbackRate: "6",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1013,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cscx18qakqticrsl6g6xvh7ha",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_CENTRIC,
      propertyName: "Hyatt Centric City Centre Kuala Lumpur",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-03-27T00:00:00.000Z",
      checkOut: "2026-04-03T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      userCreditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 35000,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cy58uq56kllc6feidriho04yh",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_PLACE,
      propertyName: "Hyatt Place Kuala Lumpur Bukit Jalil",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-04-03T00:00:00.000Z",
      checkOut: "2026-04-10T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      userCreditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 35000,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cc2gaeqcxn2mj300o28duzvd5",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.MARRIOTT,
      hotelChainSubBrandId: SUB_BRAND_ID.MARRIOTT.MOXY,
      propertyName: "Moxy Kuala Lumpur Chinatown",
      countryCode: "MY",
      city: "Kuala Lumpur",
      checkIn: "2026-04-10T00:00:00.000Z",
      checkOut: "2026-04-14T00:00:00.000Z",
      numNights: 4,
      pretaxCost: "1008.61",
      taxAmount: "181.55",
      totalCost: "1190.16",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.BRITISH_AIRWAYS,
      portalCashbackRate: "6",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "MYR",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [{ benefitType: "free_breakfast" }],
    },
    {
      id: "cpmpa0buq8jl85t5wcv13wvi8",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.MARRIOTT,
      hotelChainSubBrandId: SUB_BRAND_ID.MARRIOTT.TRIBUTE_PORTFOLIO,
      propertyName: "The Serangoon House Little India, Singapore, a Tribute Portfolio Hotel",
      countryCode: "SG",
      city: "Singapore",
      checkIn: "2026-04-14T00:00:00.000Z",
      checkOut: "2026-04-15T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "235",
      taxAmount: "46.75",
      totalCost: "281.75",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.BRITISH_AIRWAYS,
      portalCashbackRate: "6",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "SGD",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [
        { benefitType: "free_breakfast" },
        { benefitType: "dining_credit", dollarValue: "75" },
      ],
    },
    {
      id: "cmgz12kjvzu90qvn5wxrki7ui",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.ACCOR,
      hotelChainSubBrandId: SUB_BRAND_ID.ACCOR.IBIS_STYLES,
      propertyName: "ibis Styles Ambassador Incheon Airport",
      countryCode: "KR",
      city: "Incheon",
      checkIn: "2026-04-15T00:00:00.000Z",
      checkOut: "2026-04-16T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "119000",
      taxAmount: "11900",
      totalCost: "130900",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.RAKUTEN,
      portalCashbackRate: "2",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: null,
      currency: "KRW",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw2ql5z0003lb04ylkniehs",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HILTON,
      hotelChainSubBrandId: SUB_BRAND_ID.HILTON.HILTON,
      propertyName: "Hilton Frankfurt Airport",
      countryCode: "DE",
      city: "Frankfurt am Main",
      checkIn: "2026-05-11T00:00:00.000Z",
      checkOut: "2026-05-12T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "100",
      taxAmount: "2",
      totalCost: "102",
      userCreditCardId: USER_CREDIT_CARD_ID.AMEX_BUSINESS_PLATINUM,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 2299,
      pointsRedeemed: null,
      currency: "EUR",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw2zoot0004l8047g2yyq8n",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.THE_STANDARD,
      propertyName: "The Standard, Bangkok Mahanakhon",
      countryCode: "TH",
      city: "Krung Thep Maha Nakhon",
      checkIn: "2026-05-12T00:00:00.000Z",
      checkOut: "2026-05-14T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "331",
      taxAmount: "58",
      totalCost: "389",
      userCreditCardId: USER_CREDIT_CARD_ID.AMEX_PLATINUM,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 2152,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      paymentTiming: "prepaid" as PaymentTiming,
      bookingDate: "2025-10-30T00:00:00.000Z",
      bookingSource: "ota",
      otaAgencyId: OTA_AGENCY_ID.AMEX_THC,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw316zx0008l8049o59vlgs",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_REGENCY,
      propertyName: "Hyatt Regency Bangkok Sukhumvit",
      countryCode: "TH",
      city: "Krung Thep Maha Nakhon",
      checkIn: "2026-06-10T00:00:00.000Z",
      checkOut: "2026-06-12T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "0",
      taxAmount: "0",
      totalCost: "0",
      userCreditCardId: null,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: null,
      pointsRedeemed: 24000,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw33zty0003jj04n6yxbtjh",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_REGENCY,
      propertyName: "Hyatt Regency Hua Hin",
      countryCode: "TH",
      city: "Tambon Hua Hin",
      checkIn: "2026-06-12T00:00:00.000Z",
      checkOut: "2026-06-17T00:00:00.000Z",
      numNights: 5,
      pretaxCost: "17676.75",
      taxAmount: "3217.17",
      totalCost: "20893.92",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_WORLD_OF_HYATT,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 3542,
      pointsRedeemed: null,
      currency: "THB",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw39zle000alb040ivmwn4p",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.IHG,
      hotelChainSubBrandId: SUB_BRAND_ID.IHG.HOLIDAY_INN,
      propertyName: "Holiday Inn Queenstown Remarkables Park by IHG",
      countryCode: "NZ",
      city: "Queenstown",
      checkIn: "2026-08-23T00:00:00.000Z",
      checkOut: "2026-09-01T00:00:00.000Z",
      numNights: 9,
      pretaxCost: "1479.51",
      taxAmount: "221.94",
      totalCost: "1701.45",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.RAKUTEN,
      portalCashbackRate: "15",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 17319,
      pointsRedeemed: null,
      currency: "NZD",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3brv2000al804yyilr689",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.IHG,
      hotelChainSubBrandId: SUB_BRAND_ID.IHG.HOLIDAY_INN,
      propertyName: "Holiday Inn Queenstown Remarkables Park by IHG",
      countryCode: "NZ",
      city: "Queenstown",
      checkIn: "2026-09-29T00:00:00.000Z",
      checkOut: "2026-10-13T00:00:00.000Z",
      numNights: 14,
      pretaxCost: "2427.05",
      taxAmount: "364.05",
      totalCost: "2791.1",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: SHOPPING_PORTAL_ID.RAKUTEN,
      portalCashbackRate: "15",
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 28411,
      pointsRedeemed: null,
      currency: "NZD",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3hvyx0003l8045dqjuwpu",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.ACCOR,
      hotelChainSubBrandId: SUB_BRAND_ID.ACCOR.SOFITEL,
      propertyName: "Sofitel Auckland Viaduct Harbour",
      countryCode: "NZ",
      city: "Auckland",
      checkIn: "2026-10-13T00:00:00.000Z",
      checkOut: "2026-10-15T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "462",
      taxAmount: "104",
      totalCost: "566",
      userCreditCardId: USER_CREDIT_CARD_ID.AMEX_BUSINESS_PLATINUM,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1768,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      paymentTiming: "prepaid" as PaymentTiming,
      bookingDate: "2025-12-17T00:00:00.000Z",
      bookingSource: "ota",
      otaAgencyId: OTA_AGENCY_ID.AMEX_FHR,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3j15b0003ju04olm4crl1",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.IHG,
      hotelChainSubBrandId: SUB_BRAND_ID.IHG.HOTEL_INDIGO,
      propertyName: "Hotel Indigo Auckland by IHG",
      countryCode: "NZ",
      city: "Auckland",
      checkIn: "2026-10-15T00:00:00.000Z",
      checkOut: "2026-10-18T00:00:00.000Z",
      numNights: 3,
      pretaxCost: "509",
      taxAmount: "90",
      totalCost: "599",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_SAPPHIRE_RESERVE,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 10180,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      paymentTiming: "prepaid" as PaymentTiming,
      bookingDate: "2026-01-27T00:00:00.000Z",
      bookingSource: "ota",
      otaAgencyId: OTA_AGENCY_ID.CHASE_EDIT,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3kgzb0003lk04idf334zt",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_CENTRIC,
      propertyName: "Hyatt Centric Melbourne",
      countryCode: "AU",
      city: "Melbourne",
      checkIn: "2026-10-18T00:00:00.000Z",
      checkOut: "2026-10-25T00:00:00.000Z",
      numNights: 7,
      pretaxCost: "2063.88",
      taxAmount: "0",
      totalCost: "2063.88",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_WORLD_OF_HYATT,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 9505,
      pointsRedeemed: null,
      currency: "AUD",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3m2n00007ju04gfwlnk2h",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.THE_STANDARDX,
      propertyName: "The StandardX, Melbourne",
      countryCode: "AU",
      city: "Fitzroy",
      checkIn: "2026-10-25T00:00:00.000Z",
      checkOut: "2026-10-27T00:00:00.000Z",
      numNights: 2,
      pretaxCost: "415.52",
      taxAmount: "0",
      totalCost: "415.52",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_WORLD_OF_HYATT,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1914,
      pointsRedeemed: null,
      currency: "AUD",
      exchangeRate: null,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmw3nny70003la044jmw7ohd",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.PARK_HYATT,
      propertyName: "Park Hyatt Melbourne",
      countryCode: "AU",
      city: "Melbourne",
      checkIn: "2026-10-27T00:00:00.000Z",
      checkOut: "2026-10-28T00:00:00.000Z",
      numNights: 1,
      pretaxCost: "290",
      taxAmount: "29",
      totalCost: "319",
      userCreditCardId: USER_CREDIT_CARD_ID.AMEX_BUSINESS_PLATINUM,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 1885,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      paymentTiming: "prepaid" as PaymentTiming,
      bookingDate: "2026-02-07T00:00:00.000Z",
      bookingSource: "ota",
      otaAgencyId: OTA_AGENCY_ID.AMEX_FHR,
      notes: null,
      certificates: [],
      benefits: [],
    },
    {
      id: "cmmx0eb4c0003l804ttpozqdg",
      accommodationType: "hotel" as AccommodationType,
      hotelChainId: HOTEL_ID.HYATT,
      hotelChainSubBrandId: SUB_BRAND_ID.HYATT.HYATT_REGENCY,
      propertyName: "Hyatt Regency Salt Lake City",
      countryCode: "US",
      city: "Salt Lake City",
      checkIn: "2027-01-14T00:00:00.000Z",
      checkOut: "2027-01-18T00:00:00.000Z",
      numNights: 4,
      pretaxCost: "587.02",
      taxAmount: "108.71",
      totalCost: "695.73",
      userCreditCardId: USER_CREDIT_CARD_ID.CHASE_WORLD_OF_HYATT,
      shoppingPortalId: null,
      portalCashbackRate: null,
      portalCashbackOnTotal: false,
      loyaltyPointsEarned: 3816,
      pointsRedeemed: null,
      currency: "USD",
      exchangeRate: 1,
      bookingSource: "direct_web",
      otaAgencyId: null,
      notes: null,
      certificates: [],
      benefits: [],
    },
  ];

  for (const b of bookings) {
    const {
      certificates,
      benefits,
      propertyName,
      countryCode,
      city,
      accommodationType,
      ...bookingData
    } = b;

    let property = await prisma.property.findFirst({
      where: { name: propertyName, hotelChainId: bookingData.hotelChainId },
    });
    if (!property) {
      property = await prisma.property.create({
        data: { name: propertyName, hotelChainId: bookingData.hotelChainId, countryCode, city },
      });
    }

    const payload = {
      ...bookingData,
      accommodationType: accommodationType as AccommodationType,
      propertyId: property.id,
      bookingSource: bookingData.bookingSource as BookingSourceType,
      certificates: {
        create: certificates.map((c) => ({ certType: c.certType as CertType })),
      },
      benefits: {
        create: benefits.map((bf) => ({
          benefitType: bf.benefitType as BenefitType,
          dollarValue: bf.dollarValue ? Number(bf.dollarValue) : null,
        })),
      },
    };

    await prisma.booking.upsert({
      where: { id: b.id },
      update: {
        ...payload,
        userId,
        certificates: { deleteMany: {}, ...payload.certificates },
        benefits: { deleteMany: {}, ...payload.benefits },
      },
      create: { ...payload, userId },
    });
  }

  console.log("Bookings restored/upserted successfully");
}

if (require.main === module) {
  const standaloneUserId = process.env.SEED_USER_ID ?? "";
  seedBookings(standaloneUserId)
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
