export const GHA_SUB_BRAND_SLUGS: Record<string, string> = {
  anantara: "Anantara Hotels & Resorts",
  andronis: "Andronis",
  araiya: "Araiya Hotels & Resorts",
  "araiya-hotels-resorts": "Araiya Hotels & Resorts",
  "arjaan-hotel-apartments-by-rotana": "Arjaan Hotel Apartments by Rotana",
  asmallworld: "ASMALLWORLD",
  avani: "Avani Hotels & Resorts",
  "avani-hotels-resorts": "Avani Hotels & Resorts",
  "bristoria-hotels": "Bristoria Hotels",
  "campbell-gray": "Campbell Gray Hotels",
  capella: "Capella Hotels & Resorts",
  "capella-hotels-and-resorts": "Capella Hotels & Resorts",
  "centro-by-rotana": "Centro by Rotana",
  "cheval-collection": "Cheval Collection",
  "cinnamon-hotels-resorts": "Cinnamon Hotels & Resorts",
  corinthia: "Corinthia Hotels",
  "corinthia-hotels": "Corinthia Hotels",
  "divani-collection-hotels": "Divani Collection Hotels",
  "doyle-collection": "The Doyle Collection",
  "edge-by-rotana": "Edge by Rotana",
  elewana: "Elewana Collection",
  "iclub-hotels": "iclub Hotels",
  "istay-hotels": "iStay Hotels",
  "ja-resorts-hotels": "JA Resorts & Hotels",
  kempinski: "Kempinski Hotels",
  "lanson-place": "Lanson Place",
  leela: "The Leela Palaces, Hotels and Resorts",
  "lore-group": "Lore Group",
  lungarno: "Lungarno Collection",
  "lungarno-collection": "Lungarno Collection",
  maqo: "Maqo",
  "marco-polo": "Marco Polo Hotels",
  "minor-hotels": "Minor Hotels",
  "mysk-hotels": "Mysk by Shaza",
  "nh-hotels-resorts": "NH Hotels & Resorts",
  nhcollection: "NH Collection",
  nhow: "nhow Hotels",
  niccolo: "Niccolo Hotels",
  "niccolo-hotels": "Niccolo Hotels",
  "nikki-beach-hotels-resorts": "Nikki Beach Hotels & Resorts",
  nuo: "Nuo Hotels",
  oaks: "Oaks Hotels, Resorts & Suites",
  "oaks-hotels-resorts-and-suites": "Oaks Hotels, Resorts & Suites",
  omni: "Omni Hotels & Resorts",
  outrigger: "Outrigger Resorts",
  "outrigger-resorts-hotels": "Outrigger Resorts & Hotels",
  "pan-pacific": "Pan Pacific Hotels & Resorts",
  "pan-pacific-hotels-and-resorts": "Pan Pacific Hotels & Resorts",
  "paramount-hotels": "Paramount Hotels & Resorts",
  parkroyal: "PARKROYAL Hotels & Resorts",
  "parkroyal-collection-hotels-resorts": "PARKROYAL COLLECTION Hotels & Resorts",
  "parkroyal-hotels-resorts": "PARKROYAL Hotels & Resorts",
  "patina-hotels-resorts": "Patina Hotels & Resorts",
  "rayhaan-hotels-resorts-by-rotana": "Rayhaan Hotels & Resorts by Rotana",
  "regal-hotels": "Regal Hotels",
  rotana: "Rotana Hotels & Resorts",
  "rotana-hotels-resorts": "Rotana Hotels & Resorts",
  "saii-hotels-resorts": "SAii Hotels & Resorts",
  "shaza-hotels": "Shaza Hotels",
  "sun-international": "Sun International",
  "sunway-hotels-resorts": "Sunway Hotels & Resorts",
  "temptingplaces-collection": "TemptingPlaces",
  "the-residence-by-cenizaro": "The Residence by Cenizaro",
  "the-set": "The Set Hotels",
  "the-sukhothai-hotels-resorts": "The Sukhothai Hotels & Resorts",
  tivoli: "Tivoli Hotels & Resorts",
  "tivoli-hotels-and-resorts": "Tivoli Hotels & Resorts",
  "ultratravel-collection": "Ultratravel Collection",
  "unike-hoteller": "Unike Hoteller",
  viceroy: "Viceroy Hotels & Resorts",
  "verdi-hotels": "Verdi Hotels",
};

export function subBrandNameForSlug(slug: string): string {
  return (
    GHA_SUB_BRAND_SLUGS[slug] ??
    slug
      .split("-")
      .map((w) => (w.length === 0 ? w : w[0].toUpperCase() + w.slice(1)))
      .join(" ")
  );
}

export const GHA_NON_PROPERTY_SEGMENTS = new Set<string>([
  "search",
  "member",
  "our-partners",
  "destination-guides",
  "support",
]);

export const GHA_COLLECTION_SLUGS_DEPRIO = new Set<string>(["ultratravel-collection"]);
